# Generated by Django 4.2.1 on 2023-05-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folt_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("email", models.CharField(max_length=240)),
            ],
        ),
    ]
