# Generated by Django 4.2.1 on 2023-05-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folt_api", "0002_courier"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("unit", models.CharField(max_length=64)),
                ("amount", models.FloatField()),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("offer_id", models.AutoField(primary_key=True, serialize=False)),
                ("state", models.CharField(default="new", max_length=64)),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="offer_items", to="folt_api.offeritem"
                    ),
                ),
            ],
        ),
    ]
