# Generated by Django 4.2.1 on 2023-05-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folt_api", "0004_alter_offer_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pickup",
            fields=[
                ("pickup_id", models.AutoField(primary_key=True, serialize=False)),
                ("offer_id", models.PositiveIntegerField()),
                ("courier_email", models.CharField(max_length=240)),
            ],
        ),
    ]
